#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

[ -z "$STAGED_FILES" ] && exit 0

echo "Running ESLint and Prettier on staged JS/TS files..."

FILTERED_FILES=$(echo "$STAGED_FILES" | grep -Ev '(\.eslintrc\.js|\.prettierrc\.js|node_modules/)')

[ -z "$FILTERED_FILES" ] && exit 0

yarn eslint --fix $FILTERED_FILES

yarn prettier --write $FILTERED_FILES

git add $FILTERED_FILES

echo "ESLint & Prettier finished ✅"
